import enum

class PasswordConfiguration(enum.Enum):
    UPPER_CASE = 1
    LOWER_CASE = 2
    NUMBER = 3
    SPECIAL_CHARACTER = 4
    LOWER_UPPER_CASE = 5
    UPPER_CASE_NUMBER = 6
    UPPER_CASE_SPECIAL_CHARACTER = 7
    LOWER_CASE_NUMBER = 8
    NUMBER_SPECIAL_CHARACTER = 9
    LOWER_CASE_SPECIAL_CHARACTER = 10
    LOWER_UPPER_CASE_NUMBER = 11
    LOWER_UPPER_CASE_SPECIAL_CHARACTER = 12
    UPPER_CASE_SPECIAL_CHARACTER_NUMBER = 13
    LOWER_CASE_SPECIAL_CHARACTER_NUMBER = 14
    LOWER_UPPER_CASE_SPECIAL_CHARACTER_NUMBER = 15
    READABLE_NO_NUMBER = 16
    READABLE_NUMBER = 17
